version: "3"
services:
  server:
    image: backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/bank?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0.29
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=bank
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=12345678

networks:
  springmysql-net: